### ISSUE TITLE
Broken after update to plasma 5.20

### ISSUE THREAD

**Issue by ben2talk** [laloch/kwin-effect-osdclock#1]
/home/ben/.cache/yay/kwin-effect-osdclock-git/src/kwin-effect-osdclock/src/osdclock_config.cpp:39:26: error: ‘static KAboutData* KAboutData::pluginData(const QString&)’ is deprecated: Since 5.76. See API docs [-Werror=deprecated-declarations]
39 |     KCModule(KAboutData::pluginData(QStringLiteral("kwin_osdclock")), parent, args)
|                          ^~~~~~~~~~
In file included from /usr/include/KF5/KCoreAddons/KAboutData:1,
from /home/ben/.cache/yay/kwin-effect-osdclock-git/src/kwin-effect-osdclock/src/osdclock_config.cpp:29:
/usr/include/KF5/KCoreAddons/kaboutdata.h:467:24: note: declared here
467 |     static KAboutData *pluginData(const QString &componentName);
|                        ^~~~~~~~~~
/home/ben/.cache/yay/kwin-effect-osdclock-git/src/kwin-effect-osdclock/src/osdclock_config.cpp:39:68: error: ‘static KAboutData* KAboutData::pluginData(const QString&)’ is deprecated: Since 5.76. See API docs [-Werror=deprecated-declarations]
39 |     KCModule(KAboutData::pluginData(QStringLiteral("kwin_osdclock")), parent, args)
|                                                                    ^
In file included from /usr/include/KF5/KCoreAddons/KAboutData:1,
from /home/ben/.cache/yay/kwin-effect-osdclock-git/src/kwin-effect-osdclock/src/osdclock_config.cpp:29:
/usr/include/KF5/KCoreAddons/kaboutdata.h:467:24: note: declared here
467 |     static KAboutData *pluginData(const QString &componentName);
|                        ^~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [src/CMakeFiles/kwin_osdclock_config.dir/build.make:119: src/CMakeFiles/kwin_osdclock_config.dir/osdclock_config.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:292: src/CMakeFiles/kwin_osdclock_config.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
==> ERROR: A failure occurred in build().

**Comment by laloch** [comment]
Hi @ben2talk, thanks for reporting!
I'll try to fix the issue ASAP.

**Comment by laloch** [comment]
Fixed by 7999e93.

**Comment by ben2talk** [comment]
Thank you, works for me. 
    On Wednesday, 13 January 2021, 20:44:32 GMT+7, David Strobach <notifications@github.com> wrote:  
 
 


Closed #1.
