### ISSUE TITLE
cmake gets some issues

### ISSUE THREAD

**Issue by ghost** [laloch/kwin-effect-osdclock#4]
krupal@pSwaqtch:~/kwin-effect-osdclock/build$ cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib ..
-- Installing in the same prefix as Qt, adopting their path scheme.
CMake Warning (dev) at /usr/share/ECM/modules/ECMFindModuleHelpers.cmake:112 (message):
  Your project should require at least CMake 3.16.0 to use FindKF5.cmake
Call Stack (most recent call first):
  /usr/share/ECM/find-modules/FindKF5.cmake:30 (ecm_find_package_version_check)
  src/CMakeLists.txt:9 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find KF5Completion (missing: KF5Completion_DIR)
-- Could NOT find KF5Completion: found neither KF5CompletionConfig.cmake nor kf5completion-config.cmake 
-- Could NOT find KF5WindowSystem (missing: KF5WindowSystem_DIR)
-- Could NOT find KF5WindowSystem: found neither KF5WindowSystemConfig.cmake nor kf5windowsystem-config.cmake 
-- Could NOT find KF5GlobalAccel (missing: KF5GlobalAccel_DIR)
-- Could NOT find KF5GlobalAccel: found neither KF5GlobalAccelConfig.cmake nor kf5globalaccel-config.cmake 
-- Could NOT find KF5I18n (missing: KF5I18n_DIR)
-- Could NOT find KF5I18n: found neither KF5I18nConfig.cmake nor kf5i18n-config.cmake 
-- Could NOT find KF5ConfigWidgets (missing: KF5ConfigWidgets_DIR)
-- Could NOT find KF5ConfigWidgets: found neither KF5ConfigWidgetsConfig.cmake nor kf5configwidgets-config.cmake 
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find KF5 (missing: Completion WindowSystem GlobalAccel I18n
  ConfigWidgets)
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/ECM/find-modules/FindKF5.cmake:93 (find_package_handle_standard_args)
  src/CMakeLists.txt:9 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/krupal/kwin-effect-osdclock/build/CMakeFiles/CMakeOutput.log".

**Comment by ben2talk** [comment]
OSD-clock failed to build for me more than a year ago.

If nobody fixes it, I'd recommend trying out a conky clock - though not quite the same, it's almost as good:

```
conky.config = {
-- Conky settings
	background = true,
	update_interval = 5,
	double_buffer = true,
	no_buffers = true,

-- Window specifications
	gap_x = 10,
	gap_y = 50,
	alignment = 'top_right',
	own_window = true,
	own_window_type = 'dock',
	own_window_transparent = true,
	own_window_argb_visual = true,
	own_window_argb_value = 70,
	own_window_hints = 'undecorated,above,sticky,skip_taskbar,skip_pager',
	own_window_class = 'conky',

-- Text
	use_xft = true,
	xftalpha = 0.3,
	font = 'Arial Rounded MT bold :size=32',
	default_color = '#666',
};

conky.text = [[${time %H:%M}]];
```
